sudo pip install Flask==0.10.1 
sudo pip install Jinja2==2.7.3 
sudo pip install MarkupSafe==0.23 
sudo pip install Pillow==2.6.1 
sudo pip install PyAudio==0.2.8 
sudo pip install RPi.GPIO==0.6.3 
sudo pip install Werkzeug==0.9.6 
sudo pip install backports-abc==0.5 
sudo pip install blinker==1.3 
sudo pip install certifi==2017.11.5 
sudo pip install chardet==2.3.0 
sudo pip install colorama==0.3.2 
sudo pip install enum34==1.1.6 
sudo pip install gpiozero==1.3.2 
sudo pip install h2==2.6.2 
sudo pip install hpack==3.0.0 
sudo pip install html5lib==0.999 
sudo pip install hyper==0.7.0 
sudo pip install hyperframe==3.2.0 
sudo pip install itsdangerous==0.24 
sudo pip install numpy==1.8.2 
sudo pip install picamera==1.13 
sudo pip install picraft==1.0 
sudo pip install pifacecommon==4.1.2 
sudo pip install pifacedigitalio==3.0.5
sudo pip install pigpio==1.35 
sudo pip install pyOpenSSL==0.13.1 
sudo pip install pyasn1==0.1.7 
sudo pip install pygame==1.9.2 
sudo pip install pygobject==3.14.0 
sudo pip install pyinotify==0.9.4 
sudo pip install pyserial==2.6 
sudo pip install python-apt==0.9.3.12 
sudo pip install python-dateutil==2.2 
sudo pip install requests==2.4.3 
sudo pip install sense-emu==1.0 
sudo pip install sense-hat==2.2.0 
sudo pip install singledispatch==3.4.0.3 
sudo pip install six==1.8.0 
sudo pip install smbus==1.1 
sudo pip install spidev==3.0 
sudo pip install tornado==4.5.2 
sudo pip install twython==3.1.2 
sudo pip install urllib3==1.9.1 
sudo pip install wheel==0.24.0 
sudo pip install wsgiref==0.1.2